tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "hudochenkov/sshpass"

brew "ansible"
brew "git"
brew "pyenv"
brew "zsh"
brew "zsh-completions"
brew "hudochenkov/sshpass/sshpass"

cask "font-hackgen"
cask "font-hackgen-nerd"
cask "iterm2"
cask "visual-studio-code-insiders"
cask "firefox"
cask "google-chrome"
cask "slack"
cask "1password"
